language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
install:
- npm install -g hexo-cli
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "lijiangwei"
- git config user.email "544172066@qq.com"
- git add .
- git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/lijiangwei/lijiangwei.github.io.git
before_install:
- openssl aes-256-cbc -K $encrypted_cdd288e44784_key -iv $encrypted_cdd288e44784_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
