language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install -g hexo-cli
- npm install
script:
- hexo g
after_script:
- git config user.name "lijiangwei"
- git config user.email "544172066@qq.com"
- cd ./public
- git init
- git add --all .
- git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
- git push --force --quiet "git@${GE_SSH_REF}" master:master
branches:
  only:
  - next6
env:
  global:
  - GH_REF: github.com/lijiangwei/lijiangwei.github.io.git
  - GE_REF: gitee.com/lijiangwei/lijiangwei.git
  - GE_SSH_REF: gitee.com:lijiangwei/lijiangwei.git
  - secure: ba7baUEsot1mKE32a7NUJ3kARWhOSgIFxOhuKYGjE/lEYo19FoVto15IoZhfHKEHRjgTEuqtpk2hXj1+/58sb7YuwRzhvq/CyxQ85BPvvOR7awU33CmSZPwr+9APd783DnBN1yVisyxx8+oopSYD/JAJ8jTP+GqmDXl5bjzd2Y1rboknP1i5WVsoHtLMpUJH6JUDwvbAavh1qUhTwwBoCWqERVKJsmkVSD1S5XmT0quFxMdUJiZkIajOzMc0MCJ36oevOZGvq8AqpxrAz/BE14UVa4QJGKtBas/zXXw3wxxvlKgblROi1RokgDUHfIsXxljVk2z8K8k9iOXO0RyTJIDXzNn++0OIBcdUm0DWhNwHiTUGp+CiAwGexEylxisAayKn2Lz+xBUpTiO2vLq0O5ZYLnwc5rj5JEKau4AHbKcWeQQO/s5oVcwInfcv2zn24vkSfCH8UN2cBMZu8uXVTwnB+fyKheMkF1ezeG2lOuFUYL/7sna8w5hUsmVQUfd/ec6cu4ncjgAi6NLPJN7O4ydOxzp6zI9357wMAq1atcanouK7jpGKA75ON4P7/oeby6he0fjDRxNax3hnjfe05HK2Fyji1xv7jrBAxwNbNnbrRZEGl6SeTLdwHP3wm8NJjxkI+g+Pjm2yAMkXeVc9QSsSs4dyrh26CM0mP7IQqDk=
  - secure: OSVfJnQASSK0ifq/nfwp14YkPGILJugBQVlLjYM8nSH2A+G+CCbuno6U9MqtXleMTQwjelVH8Km6oatfceclG9EsvJtkaWlSd3PQqlFATamCuOkoDVjLgHvPGt7UA3JcAqKl4YnnCRyQAjy0SBsMVYduFZURQYzSGBPl+JmF/mtQjGgX/yNY6Dmqr2q0sBJafZAilJaOFX1Ws/zkRd1FshNsXMPdwbfJDj4iMRiV91UGjq1uw62zrVjykpwoMUOcRniXbH/qq87Bd36aPQsRd5LqTJd1x0BUo6hP6oE5CHnIm8RL3riiOCvtUHdpd1XAkNkhFjZStyjLzRzVY6QWVU/Mn+W/8Ggge8M6nCifcl7saaVRBOxw6P/AWHruAoW4f1UuGx+8LViMU4MHBGxltmCTOWaqxsZj9mvUxSv2i9dFqKcpcqr+sWUatjX9GdpS4B2BCywT8AKeEPWsaDlCx/IJ9Cm549C/1arAh32L7BEVOY7/ClBaY/wcsV9fLJsID2pJR8iZMrEpAp+u2YDq935XXdPMJ9ihcIvCAeXi/JU0MH+PcTLKzbGonEEJ8PIp8VQPEHajqRQ1WIvWjss3EjjfVgYwfbxV1gaS4LuUhj6FnyKHRThowEon6b5A/qxfxAIYNfWly4TH2p0O3XUXcvKvhu5FTzJt5Jlj2q7vAiM=
before_install:
- openssl aes-256-cbc -K $encrypted_cdd288e44784_key -iv $encrypted_cdd288e44784_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMuEoYdx6to5oxR60IWj8uoe1aI0X1fKOHWOtLqTg1tsLT1iFwXV5JmFjU46EzeMBV/6EmI1uaRI6HiEPtPtJHE='
  >> ~/.ssh/known_hosts
addons:
  ssh_known_hosts:
  - gitee.com
